function inlineComputedStyles(node: HTMLElement) {
  if (!(node instanceof HTMLElement)) return

  const computed = window.getComputedStyle(node)
  for (let i = 0; i < computed.length; i++) {
    const prop = computed[i]
    const val = computed.getPropertyValue(prop)
    if (val && val !== 'inherit') {
      node.style.setProperty(prop, val, computed.getPropertyPriority(prop) || undefined)
    }
  }

  for (const child of node.children) {
    inlineComputedStyles(child as HTMLElement)
  }
}

export async function printPDF(element: HTMLElement) {
  // 收集页面样式
  const cssParts: string[] = []
  for (let i = 0; i < document.styleSheets.length; i++) {
    const sheet = document.styleSheets[i]
    try {
      const rules = sheet.cssRules || sheet.rules
      for (let j = 0; j < rules.length; j++) {
        cssParts.push(rules[j].cssText)
      }
    } catch {
      // 跨域样式表跳过
    }
  }
  document.querySelectorAll('style').forEach((el) => {
    const text = el.textContent
    if (text && !cssParts.some(c => text.includes(c.substring(0, 40)))) {
      cssParts.push(text)
    }
  })

  // 克隆 + 内联计算样式
  const clone = element.cloneNode(true) as HTMLElement
  clone.style.width = '210mm'
  inlineComputedStyles(clone)

  const watermark = '<div style="text-align:center;font-size:9px;color:#999;padding:12px 0 8px;border-top:1px solid #eee;margin-top:24px">Generated by resbu.top</div>'

  const html = '<!DOCTYPE html><html><head><meta charset="utf-8"><style>' +
    '* { box-sizing: border-box; }' +
    '@page { size: A4; margin: 0; }' +
    'body { margin: 0; padding: 0; }' +
    cssParts.join('\n') +
    '</style></head><body>' +
    clone.outerHTML +
    watermark +
    '</body></html>'

  // 打开新窗口触发浏览器打印预览
  const printWindow = window.open('', '_blank', 'width=800,height=600')
  if (!printWindow) {
    throw new Error('Pop-up blocked. Please allow pop-ups for this site.')
  }

  printWindow.document.write(html)
  printWindow.document.close()

  // 等资源加载完成后触发打印
  await new Promise<void>((resolve) => {
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print()
        resolve()
      }, 300)
    }
  })
}
